### ISSUE TITLE
Missing HAVE_TSIP

### ISSUE THREAD

**Issue by rbastic** [demerphq/smhasher#1]
Howdy friend,

Been a while since I've poked at smhasher! :-)

I just hit git pull on my smhasher repository and tried to rebuild. I noticed that there seems to be a missing preprocessor conditional for the HAVE_TSIP define. Here's my patch:

--- a/main.cpp
+++ b/main.cpp
@@ -305,9 +305,11 @@ HashInfo g_hashes[] =
   { "SipHash", "SipHash 2-4",
     128, 256, 64, 0x5F4173E0,
     siphash_seed_state_test, siphash_with_state_test },
+#ifdef HAVE_TSIP
   { "TSip", "Damian Gryski's Tiny SipHash variant",
     128, 128, 64, 0x881B5461,
     tsip_seed_state_smhasher_test, tsip_hash_with_state_smhasher_test },
+#endif

Cheers,
Ryan

**Comment by demerphq** [comment]
Is this still an issue ryan?

Yves

**Comment by rbastic2** [comment]
Hi Yves,

Yes, appears so. Can you apply my patch, starting around line 318?

Ryan

**Comment by demerphq** [comment]
K, fixed. Thanks dude! Hope you are well.
