### ISSUE TITLE
Sparse-Key Test is broken and results are invalid (sure)

### ISSUE THREAD

**Issue by leo-yuriev** [demerphq/smhasher#10]
SparseKeygenRecurse() [internally re-seeding](https://github.com/demerphq/smhasher/blob/d104d96f83fce55931ee710979c5892e9484103f/KeysetTest.h#L310) from rand on each iteration.

Therefore each hash-value calculates with different seed and SparseKeyTest is   invalid, i.e. nothing testing.

Seems each call of `hash.seed_state_rand()` should be verified.

**Comment by funny-falcon** [comment]
Yeah, and here is commit that add this error: https://github.com/demerphq/smhasher/commit/50030ac6a74b5ee862188f8a04bf3b4115ae7fdc#diff-4f82ecff6c2689d8285b810d5fb6e038R313

It is clear that it was added in this commit by mistake.
